"""
Verification Engine
===================

Implements logical validators, universal verifiers, and integrity checkers
that ensure responses demonstrate exclusive knowledge while maintaining
separation boundaries.
"""

from typing import Optional, Dict, Any, List, Tuple, Callable
from dataclasses import dataclass, field
from enum import Enum
import hashlib
from ..core.realms import LogicalState, SharedRealm, SeparateRealm
from ..core.state import LogicalBoundary, StateType
from ..foundation.axioms import SharedAxiom, SharedMethod, SharedWitness
from ..protocol.challenge import Challenge, ChallengeResponse


class VerificationResult(Enum):
    """Result of a verification attempt."""
    VALID = "VALID"
    INVALID = "INVALID"
    INSUFFICIENT_PROOF = "INSUFFICIENT_PROOF"
    BOUNDARY_VIOLATION = "BOUNDARY_VIOLATION"
    TIMEOUT = "TIMEOUT"
    REQUIRES_WITNESS = "REQUIRES_WITNESS"


@dataclass
class VerificationReport:
    """Detailed report of a verification attempt."""
    result: VerificationResult
    entity_id: str
    challenge_id: Optional[str]
    checks_performed: List[str]
    checks_passed: List[str]
    checks_failed: List[str]
    reason: str
    timestamp: float
    
    def is_successful(self) -> bool:
        """Check if verification was successful."""
        return self.result == VerificationResult.VALID
        
    def get_success_rate(self) -> float:
        """Calculate the success rate of checks."""
        total = len(self.checks_performed)
        if total == 0:
            return 0.0
        return len(self.checks_passed) / total


class LogicalValidator:
    """
    Ensures responses demonstrate exclusive knowledge.
    
    This validator checks that responses could only have been
    generated by an entity with access to exclusive knowledge.
    """
    
    def __init__(self, shared_axioms: SharedAxiom):
        """
        Initialize the logical validator.
        
        Args:
            shared_axioms: Reference to shared axioms
        """
        self._axioms = shared_axioms
        self._validation_rules: List[Callable] = []
        self._register_validation_rules()
        
    def _register_validation_rules(self):
        """Register core validation rules."""
        
        def rule_non_trivial(response: ChallengeResponse) -> Tuple[bool, str]:
            """Check that response is non-trivial."""
            if not response.proofs:
                return False, "No proofs provided"
            for proof in response.proofs.values():
                if len(proof) < 32:  # Minimum entropy requirement
                    return False, "Proof lacks sufficient entropy"
            return True, "Response is non-trivial"
            
        def rule_deterministic(response: ChallengeResponse) -> Tuple[bool, str]:
            """Check that response is deterministic."""
            # Same entity should produce same response for same challenge
            proof_hashes = [hashlib.sha256(p.encode()).hexdigest()[:8] 
                           for p in response.proofs.values()]
            if len(set(proof_hashes)) != len(proof_hashes):
                return False, "Proofs are not independently generated"
            return True, "Response is deterministic"
            
        def rule_incorporates_challenge(response: ChallengeResponse) -> Tuple[bool, str]:
            """Check that response incorporates the challenge."""
            challenge_id_hash = hashlib.sha256(response.challenge_id.encode()).hexdigest()
            for proof in response.proofs.values():
                # Proof should be different from just hashing the challenge
                if proof == challenge_id_hash:
                    return False, "Proof doesn't incorporate exclusive knowledge"
            return True, "Response incorporates challenge"
            
        self._validation_rules.extend([
            rule_non_trivial,
            rule_deterministic,
            rule_incorporates_challenge
        ])
        
    def validate_response(self, challenge: Challenge,
                         response: ChallengeResponse) -> VerificationReport:
        """
        Validate that a response demonstrates exclusive knowledge.
        
        Args:
            challenge: The original challenge
            response: The response to validate
            
        Returns:
            VerificationReport with results
        """
        checks_performed = []
        checks_passed = []
        checks_failed = []
        
        # Apply each validation rule
        for rule in self._validation_rules:
            rule_name = rule.__name__
            checks_performed.append(rule_name)
            
            passed, reason = rule(response)
            if passed:
                checks_passed.append(rule_name)
            else:
                checks_failed.append(rule_name)
                
        # Check axiom compliance
        axiom_check = "axiom_compliance"
        checks_performed.append(axiom_check)
        
        response_state = response.to_logical_state()
        challenge_state = challenge.to_logical_state()
        
        if self._axioms.verify_consistency(challenge_state, response_state):
            checks_passed.append(axiom_check)
        else:
            checks_failed.append(axiom_check)
            
        # Determine overall result
        if len(checks_failed) == 0:
            result = VerificationResult.VALID
            reason = "All validation checks passed"
        elif len(checks_passed) > len(checks_failed):
            result = VerificationResult.INSUFFICIENT_PROOF
            reason = f"Some validation checks failed: {', '.join(checks_failed)}"
        else:
            result = VerificationResult.INVALID
            reason = f"Multiple validation failures: {', '.join(checks_failed)}"
            
        return VerificationReport(
            result=result,
            entity_id=response.entity_id,
            challenge_id=challenge.id,
            checks_performed=checks_performed,
            checks_passed=checks_passed,
            checks_failed=checks_failed,
            reason=reason,
            timestamp=LogicalState(content="").timestamp
        )
        
    def add_validation_rule(self, rule: Callable) -> None:
        """Add a custom validation rule."""
        self._validation_rules.append(rule)


class UniversalVerifier:
    """
    Allows any entity to validate using shared axioms.
    
    This verifier operates entirely on shared knowledge and logical
    principles, enabling distributed verification without central authority.
    """
    
    def __init__(self, shared_realm: SharedRealm, shared_methods: SharedMethod,
                 shared_witness: SharedWitness):
        """
        Initialize the universal verifier.
        
        Args:
            shared_realm: Reference to shared realm
            shared_methods: Available shared methods
            shared_witness: Witness system
        """
        self._shared_realm = shared_realm
        self._shared_methods = shared_methods
        self._shared_witness = shared_witness
        
    def verify_entity_claim(self, entity_id: str, claim: LogicalState) -> bool:
        """
        Verify an entity's claim using only shared knowledge.
        
        Args:
            entity_id: ID of entity making claim
            claim: The claim to verify
            
        Returns:
            True if claim can be verified
        """
        # Check if claim has been witnessed
        if self._shared_witness.is_witnessed(claim):
            return True
            
        # Check if entity has registered commitment for this claim
        commitment = self._shared_realm.get_commitment(entity_id)
        if commitment and commitment.content.get('entity') == entity_id:
            # Verify claim is consistent with commitment
            claim_hash = hashlib.sha256(str(claim.content).encode()).hexdigest()[:16]
            if commitment.content.get('proof_hash') == claim_hash:
                return True
                
        return False
        
    def verify_authentication(self, entity_id: str, challenge: Challenge,
                             response: ChallengeResponse) -> VerificationReport:
        """
        Verify an authentication attempt using universal principles.
        
        Args:
            entity_id: ID of entity being authenticated
            challenge: The challenge issued
            response: The response provided
            
        Returns:
            VerificationReport with results
        """
        checks_performed = []
        checks_passed = []
        checks_failed = []
        
        # Check 1: Entity matches
        check_name = "entity_match"
        checks_performed.append(check_name)
        if response.entity_id == entity_id and challenge.target_entity == entity_id:
            checks_passed.append(check_name)
        else:
            checks_failed.append(check_name)
            
        # Check 2: Timing validity
        check_name = "timing_valid"
        checks_performed.append(check_name)
        time_diff = response.timestamp - challenge.timestamp
        if 0 < time_diff < challenge.parameters.time_window:
            checks_passed.append(check_name)
        else:
            checks_failed.append(check_name)
            
        # Check 3: Proof structure
        check_name = "proof_structure"
        checks_performed.append(check_name)
        expected_steps = len(challenge.content['operations'])
        actual_steps = len(response.proofs)
        if expected_steps == actual_steps:
            checks_passed.append(check_name)
        else:
            checks_failed.append(check_name)
            
        # Check 4: Witness requirement
        if challenge.parameters.requires_witness:
            check_name = "witness_requirement"
            checks_performed.append(check_name)
            if len(response.witnesses) >= 2:
                checks_passed.append(check_name)
            else:
                checks_failed.append(check_name)
                
        # Check 5: Method validity
        check_name = "method_validity"
        checks_performed.append(check_name)
        valid_methods = ['hash_combine', 'derive_proof', 'boundary_transform']
        if response.method_used in valid_methods:
            checks_passed.append(check_name)
        else:
            checks_failed.append(check_name)
            
        # Determine result
        if len(checks_failed) == 0:
            result = VerificationResult.VALID
            reason = "Authentication successful"
        elif 'timing_valid' in checks_failed:
            result = VerificationResult.TIMEOUT
            reason = "Response outside time window"
        elif 'witness_requirement' in checks_failed:
            result = VerificationResult.REQUIRES_WITNESS
            reason = "Insufficient witnesses"
        else:
            result = VerificationResult.INVALID
            reason = f"Authentication failed: {', '.join(checks_failed)}"
            
        return VerificationReport(
            result=result,
            entity_id=entity_id,
            challenge_id=challenge.id,
            checks_performed=checks_performed,
            checks_passed=checks_passed,
            checks_failed=checks_failed,
            reason=reason,
            timestamp=LogicalState(content="").timestamp
        )
        
    def can_verify(self, entity_id: str) -> bool:
        """
        Check if an entity can be verified.
        
        Args:
            entity_id: ID of entity to check
            
        Returns:
            True if entity has registered boundary commitment
        """
        commitment = self._shared_realm.get_commitment(entity_id)
        return commitment is not None


class IntegrityChecker:
    """
    Confirms separation boundaries remain intact.
    
    This ensures that the fundamental distinction between SHARED
    and SEPARATE is maintained throughout the protocol.
    """
    
    def __init__(self, logical_boundary: LogicalBoundary):
        """
        Initialize the integrity checker.
        
        Args:
            logical_boundary: Reference to logical boundary system
        """
        self._logical_boundary = logical_boundary
        self._integrity_log: List[Dict] = []
        
    def check_boundary_integrity(self, entity_id: str) -> Tuple[bool, str]:
        """
        Check if an entity's boundary maintains integrity.
        
        Args:
            entity_id: ID of entity to check
            
        Returns:
            Tuple of (is_intact, reason)
        """
        boundary = self._logical_boundary.get_boundary(entity_id)
        if not boundary:
            return False, "No boundary exists for entity"
            
        # Check if boundary has exclusive knowledge
        if not boundary.has_exclusive_knowledge():
            return False, "Boundary has no exclusive knowledge"
            
        # Check if separation marker is valid
        marker = boundary.get_separation_marker()
        if len(marker) != 64:  # SHA-256 hex length
            return False, "Invalid separation marker"
            
        # Verify boundary commitment exists
        commitment = self._logical_boundary.get_boundary_commitment(entity_id)
        if not commitment:
            return False, "No boundary commitment registered"
            
        self._log_integrity_check(entity_id, True, "Boundary intact")
        return True, "Boundary integrity confirmed"
        
    def check_separation_maintained(self, entity_id: str,
                                   knowledge: LogicalState) -> bool:
        """
        Verify that claimed exclusive knowledge is properly separated.
        
        Args:
            entity_id: ID of entity claiming knowledge
            knowledge: The knowledge being claimed
            
        Returns:
            True if separation is maintained
        """
        # Use logical boundary to verify separation
        is_separated = self._logical_boundary.verify_separation(entity_id, knowledge)
        
        reason = "Separation maintained" if is_separated else "Separation violated"
        self._log_integrity_check(entity_id, is_separated, reason)
        
        return is_separated
        
    def verify_no_boundary_crossing(self, shared_realm: SharedRealm,
                                   entity_id: str) -> bool:
        """
        Verify that no exclusive knowledge has leaked to shared realm.
        
        Args:
            shared_realm: The shared realm to check
            entity_id: Entity whose boundary to check
            
        Returns:
            True if no boundary crossing detected
        """
        boundary = self._logical_boundary.get_boundary(entity_id)
        if not boundary:
            return True  # No boundary to cross
            
        # Check if any exclusive knowledge appears in shared realm
        # This would be a fundamental protocol violation
        
        # We can't directly check exclusive knowledge (it's exclusive)
        # But we can verify that boundary proofs don't appear in shared
        
        commitment = self._logical_boundary.get_boundary_commitment(entity_id)
        if commitment:
            # The commitment should only contain public proof, not exclusive data
            if 'exclusive' in str(commitment.content).lower():
                self._log_integrity_check(entity_id, False, "Potential boundary crossing")
                return False
                
        self._log_integrity_check(entity_id, True, "No boundary crossing detected")
        return True
        
    def _log_integrity_check(self, entity_id: str, passed: bool, reason: str):
        """Log an integrity check result."""
        self._integrity_log.append({
            'entity_id': entity_id,
            'passed': passed,
            'reason': reason,
            'timestamp': LogicalState(content="").timestamp
        })
        
    def get_integrity_report(self, entity_id: Optional[str] = None) -> Dict:
        """
        Get integrity report for an entity or all entities.
        
        Args:
            entity_id: Optional specific entity to report on
            
        Returns:
            Integrity report dictionary
        """
        if entity_id:
            checks = [c for c in self._integrity_log if c['entity_id'] == entity_id]
        else:
            checks = self._integrity_log
            
        if not checks:
            return {
                'total_checks': 0,
                'passed': 0,
                'failed': 0,
                'success_rate': 0.0,
                'recent_checks': []
            }
            
        passed = sum(1 for c in checks if c['passed'])
        failed = len(checks) - passed
        
        return {
            'total_checks': len(checks),
            'passed': passed,
            'failed': failed,
            'success_rate': passed / len(checks),
            'recent_checks': checks[-5:]  # Last 5 checks
        }